### ISSUE TITLE
feat: Add Google Pay Payment Integration

### ISSUE THREAD

**Issue by AyendiSimeon1** [tekpriest/paystack-node#17]
### **Description**
As a merchant using Paystack, I would like to offer my customers the ability to make payments using Google Pay. This would provide an additional convenient payment option and help increase conversion rates.

**Proposed Implementation:**

1. Integrate with the Google Pay API to enable accepting Google Pay transactions.
2. Implement the necessary backend logic to handle Google Pay payment requests and process them through Paystack.
3. Ensure a smooth user experience by seamlessly integrating the Google Pay flow into the existing Paystack payment interfaces.
4. Add comprehensive test coverage to validate the Google Pay integration.
5. Document the new Google Pay functionality in the project's README and contribution guidelines.

**Success Criteria:**

1. Customers can successfully complete payments using Google Pay on the Paystack platform.
2. Google Pay transactions are properly processed and reconciled through Paystack.
3. No regressions or issues with existing payment functionality after Google Pay integration.
4. Clear documentation is available for developers to understand and use the Google Pay feature.

**Comment by tekpriest** [comment]
hey @AyendiSimeon1, the package works as wrapper for Paystack API and will only provide functions for payments supported by Paystack. When Paystack adds Google Pay integration, I will be glad to include it, contributions are also welcome.
