### ISSUE TITLE
Issue with fetching plans

### ISSUE THREAD

**Issue by waptik** [tekpriest/paystack-node#5]
I tried fetching plans but got an error as seen below:

```sh
SyntaxError: Unexpected end of JSON input
web:dev:     at JSON.parse (<anonymous>)
web:dev:     at Plan.<anonymous> (/home/waptik/Projects/monorepo/turbo/node_modules/paystack-sdk/dist/plan/plan.js:46:25)
web:dev:     at Generator.next (<anonymous>)
web:dev:     at fulfilled (/home/waptik/Projects/monorepo/turbo/node_modules/paystack-sdk/dist/plan/plan.js:5:58)
web:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

The code 

```ts
const plans = await paystack.plan.list();
    console.log({ plans });
```

**Comment by waptik** [comment]
There's definately something wrong this api endpoints cos i get error when i try most of the examples at https://github.com/tekpriest/paystack-node/tree/main/src/plan

**Comment by tekpriest** [comment]
I will check on this and push a fix

**Comment by tekpriest** [comment]
fixed in https://github.com/tekpriest/paystack-node/commit/6c49cb0ad290ed00b32d851e51c1addb441ca825 #

**Comment by waptik** [comment]
> fixed in https://github.com/tekpriest/paystack-node/commit/6c49cb0ad290ed00b32d851e51c1addb441ca825

Thanks for the quick fix
